import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#c9dbf9",
        "secondary-fixed": "#eaddff",
        "on-tertiary-fixed": "#380d00",
        "on-secondary-container": "#60537f",
        "on-secondary-fixed": "#20143c",
        secondary: "#655784",
        "inverse-primary": "#c9bfff",
        "on-primary": "#ffffff",
        "tertiary-container": "#ce4700",
        primary: "#5b3cdd",
        "tertiary-fixed": "#ffdbcf",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface-container-highest": "#d3e3ff",
        "secondary-container": "#dac9fd",
        "on-tertiary-fixed-variant": "#802900",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb59a",
        "primary-fixed-dim": "#c9bfff",
        "on-background": "#091c32",
        "secondary-fixed-dim": "#cfbef2",
        error: "#ba1a1a",
        "on-surface-variant": "#484555",
        tertiary: "#a43700",
        "inverse-on-surface": "#ebf1ff",
        outline: "#797587",
        "on-tertiary": "#ffffff",
        surface: "#F8F9FF",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#441cc8",
        "on-primary-fixed": "#1a0063",
        "on-secondary": "#ffffff",
        "surface-tint": "#5d3fe0",
        "outline-variant": "#c9c4d8",
        background: "#f8f9ff",
        "on-primary-container": "#fffbff",
        "surface-container-high": "#dde9ff",
        "primary-fixed": "#e5deff",
        "surface-container-low": "#eff4ff",
        "surface-variant": "#d3e3ff",
        "surface-container": "#E6EEFF",
        "on-surface": "#091c32",
        "on-error-container": "#93000a",
        "primary-container": "#7459f7",
        "inverse-surface": "#203148",
        "on-secondary-fixed-variant": "#4d406b",
        "lavender-tint": "#7B61FF"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-margin": "1rem",
        "sidebar-width": "72px",
        "gutter-md": "1.5rem",
        "stack-xs": "0.25rem",
        "stack-lg": "2rem",
        "stack-sm": "0.5rem",
        "margin-desktop": "32px",
        unit: "4px",
        "margin-mobile": "16px",
        "container-padding": "32px",
        gutter: "24px"
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "mono-data": ["Hanken Grotesk", "sans-serif"],
        button: ["Hanken Grotesk", "sans-serif"],
        "body-rt": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        subheading: ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {lineHeight: "20px", fontWeight: "500"}],
        "headline-md": ["32px", {lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600"}],
        "label-lg": ["13px", {lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600"}],
        "headline-lg": ["32px", {lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700"}],
        "label-md": ["11px", {lineHeight: "14px", fontWeight: "600"}],
        "headline-lg-mobile": ["28px", {lineHeight: "36px", fontWeight: "700"}],
        "body-lg": ["16px", {lineHeight: "24px", fontWeight: "500"}],
        "mono-data": ["12px", {lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400"}],
        button: ["14px", {lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600"}],
        "body-rt": ["16px", {lineHeight: "24px", letterSpacing: "0", fontWeight: "400"}],
        "display-lg": ["48px", {lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700"}],
        "label-sm": ["12px", {lineHeight: "16px", letterSpacing: "0", fontWeight: "500"}],
        subheading: ["20px", {lineHeight: "28px", letterSpacing: "0", fontWeight: "500"}],
        "display-lg-mobile": ["32px", {lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700"}]
      }
    },
  },
  plugins: [],
};
export default config;
