"use client";

import { useMemo, useState } from "react";
import { Download, MoreHorizontal, ShieldAlert, UserCheck, Users } from "lucide-react";
import { adminUsers, AdminStatus } from "@/components/admin/admin-data";
import { EmptyState, FilterPills, PageHeader, SearchField, StatCard, StatusBadge, Toast, secondaryButton, useAdminToast } from "@/components/admin/AdminUI";

export default function UsersPage() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  const [usersList, setUsersList] = useState(adminUsers); const { toast, showToast, clearToast } = useAdminToast();
  const filtered = useMemo(() => usersList.filter((user) => (filter === "all" || user.type.toLowerCase() === filter || user.status === filter) && `${user.name} ${user.email} ${user.country}`.toLowerCase().includes(query.toLowerCase())), [query, filter, usersList]);
  const toggleUser = (id: string) => setUsersList((current) => current.map((user) => user.id === id ? { ...user, status: (user.status === "suspended" ? "active" : "suspended") as AdminStatus } : user));
  const exportUsers = () => { const blob = new Blob([["Name,Email,Type,Country,Status", ...filtered.map((u) => `${u.name},${u.email},${u.type},${u.country},${u.status}`)].join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "proov-users.csv"; link.click(); URL.revokeObjectURL(url); showToast("User export downloaded"); };
  return <div className="space-y-7"><PageHeader eyebrow="Platform" title="Users" description="Manage buyers, manufacturers, access, and account health." actions={<button onClick={exportUsers} className={secondaryButton}><Download size={15} />Export</button>} />
    <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Total accounts" value="1,284" detail="+46 this month" icon={<Users size={18} />} /><StatCard label="Verified manufacturers" value="142" detail="91% approval rate" icon={<UserCheck size={18} />} tone="emerald" /><StatCard label="Restricted accounts" value="7" detail="3 pending appeal" icon={<ShieldAlert size={18} />} tone="rose" /></div>
    <section className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="flex flex-col gap-3 border-b border-zinc-200 p-4 sm:flex-row sm:items-center sm:justify-between"><SearchField value={query} onChange={setQuery} placeholder="Search users or email..." /><FilterPills options={["all", "buyer", "manufacturer", "suspended"]} value={filter} onChange={setFilter} /></div>
      {filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-zinc-200 bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><th className="px-5 py-3">Account</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Country</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">GMV</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-100">{filtered.map((user) => <tr key={user.id} className="hover:bg-zinc-50"><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-zinc-100 text-[11px] font-bold text-zinc-600">{user.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><span><span className="block text-xs font-semibold text-zinc-900">{user.name}</span><span className="block text-[11px] text-zinc-400">{user.email}</span></span></div></td><td className="px-4 py-3 text-xs text-zinc-600">{user.type}</td><td className="px-4 py-3 text-xs text-zinc-600">{user.country}</td><td className="px-4 py-3 text-xs text-zinc-600">{user.orders}</td><td className="px-4 py-3 text-xs font-semibold text-zinc-700">${user.value.toLocaleString()}</td><td className="px-4 py-3"><StatusBadge status={user.status} /></td><td className="px-5 py-3 text-right"><button title={user.status === "suspended" ? "Restore account" : "Suspend account"} onClick={() => { toggleUser(user.id); showToast(user.status === "suspended" ? `${user.name} restored` : `${user.name} suspended`); }} className="rounded-md border border-zinc-200 p-1.5 text-zinc-500 hover:bg-zinc-100"><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No users found" description="Try a broader search or change the active filter." /></div>}
    </section>{toast && <Toast message={toast} onClose={clearToast} />}</div>;
}

