"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, CircleDollarSign, Download, Package, Truck, X } from "lucide-react";
import { adminOrders, AdminStatus } from "@/components/admin/admin-data";
import { EmptyState, FilterPills, PageHeader, SearchField, StatCard, StatusBadge, Toast, primaryButton, secondaryButton, useAdminToast } from "@/components/admin/AdminUI";

export default function OrdersPage() {
  const [orders, setOrders] = useState(adminOrders); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [selectedId, setSelectedId] = useState<string | null>(null); const { toast, showToast, clearToast } = useAdminToast();
  const filtered = useMemo(() => orders.filter((order) => (filter === "all" || order.status === filter) && `${order.id} ${order.title} ${order.buyer} ${order.manufacturer}`.toLowerCase().includes(query.toLowerCase())), [orders, query, filter]);
  const selected = orders.find((order) => order.id === selectedId);
  const updateOrder = (status: AdminStatus, progress: number) => { if (!selected) return; setOrders((items) => items.map((item) => item.id === selected.id ? { ...item, status, progress } : item)); showToast(`${selected.id} moved to ${status}`); };
  return <div className="space-y-7"><PageHeader eyebrow="Operations" title="Orders" description="Oversee production, milestones, escrow state, and delivery across every active order." actions={<button onClick={() => showToast("Order report prepared for download")} className={secondaryButton}><Download size={15} />Export report</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active orders" value="48" detail="$412k in production" icon={<Package size={18} />} /><StatCard label="Funded escrow" value="$186.4k" detail="Across 31 orders" icon={<CircleDollarSign size={18} />} tone="emerald" /><StatCard label="Due this week" value="9" detail="2 need attention" icon={<Truck size={18} />} tone="amber" /><StatCard label="On-time rate" value="94.1%" detail="+2.4 pts this quarter" icon={<CheckCircle2 size={18} />} tone="emerald" /></div>
    <section className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="flex flex-col gap-3 border-b border-zinc-200 p-4 xl:flex-row xl:items-center xl:justify-between"><SearchField value={query} onChange={setQuery} placeholder="Search order or counterparty..." /><FilterPills options={["all", "open", "in production", "quality check", "shipped", "under review"]} value={filter} onChange={setFilter} /></div>
      {filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[970px] text-left"><thead><tr className="border-b border-zinc-200 bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><th className="px-5 py-3">Order</th><th className="px-4 py-3">Parties</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Production</th><th className="px-4 py-3">Escrow</th><th className="px-4 py-3">Due</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-zinc-100">{filtered.map((order) => <tr key={order.id} onClick={() => setSelectedId(order.id)} className="cursor-pointer hover:bg-zinc-50"><td className="px-5 py-3"><p className="text-xs font-semibold text-zinc-900">{order.title}</p><p className="mt-0.5 text-[11px] text-zinc-400">{order.id} · {order.units.toLocaleString()} units</p></td><td className="px-4 py-3"><p className="text-xs text-zinc-700">{order.buyer}</p><p className="text-[11px] text-zinc-400">{order.manufacturer}</p></td><td className="px-4 py-3 text-xs font-semibold text-zinc-700">${order.value.toLocaleString()}</td><td className="px-4 py-3"><StatusBadge status={order.status} /><div className="mt-2 h-1 w-24 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-violet-500" style={{ width: `${order.progress}%` }} /></div></td><td className="px-4 py-3"><StatusBadge status={order.escrow} /></td><td className="px-4 py-3 text-xs text-zinc-600">{order.due}</td><td className="px-5 py-3 text-right"><ChevronRight size={16} className="ml-auto text-zinc-300" /></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No orders found" description="Try a broader search or another lifecycle status." /></div>}
    </section>
    {selected && <><button aria-label="Close order details" className="fixed inset-0 z-40 bg-zinc-950/20" onClick={() => setSelectedId(null)} /><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto border-l border-zinc-200 bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-zinc-200 bg-white px-5 py-4"><div><p className="text-[11px] font-bold uppercase tracking-wider text-violet-600">{selected.id}</p><h2 className="mt-0.5 font-semibold text-zinc-950">Order control</h2></div><button onClick={() => setSelectedId(null)} className="rounded-lg border border-zinc-200 p-2 text-zinc-500"><X size={17} /></button></div><div className="space-y-6 p-5"><div><h3 className="text-lg font-semibold text-zinc-950">{selected.title}</h3><p className="mt-1 text-sm text-zinc-500">{selected.buyer} with {selected.manufacturer}</p></div><div className="grid grid-cols-2 gap-3"><Detail label="Order value" value={`$${selected.value.toLocaleString()}`} /><Detail label="Quantity" value={`${selected.units.toLocaleString()} units`} /><Detail label="Due date" value={selected.due} /><Detail label="Escrow" value={selected.escrow} /></div><section><div className="mb-3 flex justify-between"><h3 className="text-sm font-semibold">Milestone progress</h3><span className="text-xs text-zinc-500">{selected.progress}%</span></div><div className="h-2 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-violet-600" style={{ width: `${selected.progress}%` }} /></div><div className="mt-4 space-y-3">{["M0 · Sample approval", "M1 · Production start", "M2 · Quality check", "M3 · Delivery"].map((item, index) => <div key={item} className="flex items-center gap-3 text-xs"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${selected.progress >= (index + 1) * 25 ? "bg-emerald-100 text-emerald-700" : "bg-zinc-100 text-zinc-400"}`}>{selected.progress >= (index + 1) * 25 ? <CheckCircle2 size={14} /> : index}</span><span className="text-zinc-700">{item}</span></div>)}</div></section><section className="rounded-xl border border-zinc-200 bg-zinc-50 p-4"><h3 className="text-sm font-semibold">Admin actions</h3><p className="mt-1 text-xs text-zinc-500">Changes are recorded in the audit log.</p><div className="mt-4 grid gap-2"><button onClick={() => updateOrder("quality check", 75)} className={primaryButton}>Advance to quality check</button><button onClick={() => showToast(`Escrow ledger opened for ${selected.id}`)} className={secondaryButton}>Open escrow ledger</button><button onClick={() => { updateOrder("under review", selected.progress); }} className="h-9 rounded-lg border border-rose-200 bg-white text-sm font-semibold text-rose-600 hover:bg-rose-50">Place order on hold</button></div></section></div></aside></>}
    {toast && <Toast message={toast} onClose={clearToast} />}</div>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-zinc-200 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-1 text-xs font-semibold capitalize text-zinc-800">{value}</p></div>; }

