"use client";

import { useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, CircleDollarSign, RefreshCcw, WalletCards } from "lucide-react";
import { adminPayouts, AdminStatus } from "@/components/admin/admin-data";
import { EmptyState, FilterPills, PageHeader, SearchField, StatCard, StatusBadge, Toast, primaryButton, secondaryButton, useAdminToast } from "@/components/admin/AdminUI";

export default function PayoutsPage() {
  const [payouts, setPayouts] = useState(adminPayouts); const [filter, setFilter] = useState("all"); const [query, setQuery] = useState(""); const { toast, showToast, clearToast } = useAdminToast();
  const filtered = useMemo(() => payouts.filter((payout) => (filter === "all" || payout.status === filter) && `${payout.id} ${payout.order} ${payout.manufacturer}`.toLowerCase().includes(query.toLowerCase())), [payouts, filter, query]);
  const update = (id: string, status: AdminStatus) => { setPayouts((items) => items.map((item) => item.id === id ? { ...item, status } : item)); showToast(`${id} marked ${status}`); };
  return <div className="space-y-7"><PageHeader eyebrow="Finance" title="Payouts" description="Review milestone releases, payment rails, platform fees, and failed transfers." actions={<button onClick={() => showToast("Payout statuses synced")} className={secondaryButton}><RefreshCcw size={15} />Sync status</button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Awaiting approval" value="$7,459" detail="2 milestone releases" icon={<WalletCards size={18} />} tone="amber" /><StatCard label="Processing" value="$6,415" detail="1 transfer in flight" icon={<CircleDollarSign size={18} />} /><StatCard label="Paid this month" value="$82.6k" detail="Across 29 releases" icon={<CheckCircle2 size={18} />} tone="emerald" /><StatCard label="Failed" value="1" detail="Needs rail correction" icon={<AlertCircle size={18} />} tone="rose" /></div>
    <section className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="flex flex-col gap-3 border-b border-zinc-200 p-4 lg:flex-row lg:items-center lg:justify-between"><SearchField value={query} onChange={setQuery} placeholder="Search payout or order..." /><FilterPills options={["all", "pending", "processing", "completed", "failed"]} value={filter} onChange={setFilter} /></div>
      {filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-zinc-200 bg-zinc-50 text-[10px] uppercase tracking-wider text-zinc-400"><th className="px-5 py-3">Payout</th><th className="px-4 py-3">Manufacturer</th><th className="px-4 py-3">Milestone</th><th className="px-4 py-3">Gross / Fee</th><th className="px-4 py-3">Net</th><th className="px-4 py-3">Rail</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-zinc-100">{filtered.map((payout) => <tr key={payout.id} className="hover:bg-zinc-50"><td className="px-5 py-3"><p className="text-xs font-semibold text-zinc-900">{payout.id}</p><p className="text-[11px] text-zinc-400">{payout.order} · {payout.created}</p></td><td className="px-4 py-3 text-xs text-zinc-700">{payout.manufacturer}</td><td className="px-4 py-3 text-xs text-zinc-600">{payout.milestone}</td><td className="px-4 py-3 text-xs text-zinc-600">${payout.gross.toLocaleString()} <span className="text-zinc-400">/ ${payout.fee.toFixed(2)}</span></td><td className="px-4 py-3 text-xs font-semibold text-zinc-800">${payout.net.toLocaleString()}</td><td className="px-4 py-3 text-xs text-zinc-600">{payout.method}</td><td className="px-4 py-3"><StatusBadge status={payout.status} /></td><td className="px-5 py-3 text-right">{payout.status === "pending" && <button onClick={() => update(payout.id, "processing")} className={`${primaryButton} !h-8 !px-3 !text-xs`}>Approve</button>}{payout.status === "failed" && <button onClick={() => update(payout.id, "pending")} className={`${secondaryButton} !h-8 !px-3 !text-xs`}>Retry</button>}{!["pending", "failed"].includes(payout.status) && <button onClick={() => showToast(`${payout.id} ledger entry opened`)} className={`${secondaryButton} !h-8 !px-3 !text-xs`}>Details</button>}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No payouts found" description="Try another status or search term." /></div>}
    </section>{toast && <Toast message={toast} onClose={clearToast} />}</div>;
}

