"use client";

import { useState } from "react";
import { BellRing, Coins, Save, Shield, SlidersHorizontal } from "lucide-react";
import { PageHeader, Toast, primaryButton, useAdminToast } from "@/components/admin/AdminUI";

export default function SettingsPage() {
  const [settings, setSettings] = useState({ fee: "1.0", reviewSla: "72", bidLimit: "20", autoRisk: true, payoutApproval: true, disputeAlerts: true, verificationAlerts: true }); const { toast, showToast, clearToast } = useAdminToast();
  const update = (key: keyof typeof settings, value: string | boolean) => setSettings((current) => ({ ...current, [key]: value }));
  return <div className="space-y-7"><PageHeader eyebrow="Platform" title="Settings" description="Control marketplace policy, fees, risk checks, approvals, and admin notifications." actions={<button onClick={() => showToast("Platform settings saved and audited")} className={primaryButton}><Save size={15} />Save changes</button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5"><SettingsSection icon={<Coins size={18} />} title="Marketplace economics" description="Fees and manufacturer participation limits."><div className="grid gap-4 sm:grid-cols-2"><Field label="Platform commission (%)" value={settings.fee} onChange={(value) => update("fee", value)} suffix="%" /><Field label="Monthly free bid quota" value={settings.bidLimit} onChange={(value) => update("bidLimit", value)} suffix="bids" /></div></SettingsSection>
      <SettingsSection icon={<Shield size={18} />} title="Risk and governance" description="Guardrails for manual review and financial actions."><div className="grid gap-4 sm:grid-cols-2"><Field label="Dispute review SLA" value={settings.reviewSla} onChange={(value) => update("reviewSla", value)} suffix="hours" /><Toggle label="Automatic market risk scans" description="Flag unusual bid velocity and pricing." checked={settings.autoRisk} onChange={(value) => update("autoRisk", value)} /><Toggle label="Two-person payout approval" description="Require a second admin above $10,000." checked={settings.payoutApproval} onChange={(value) => update("payoutApproval", value)} /></div></SettingsSection>
      <SettingsSection icon={<BellRing size={18} />} title="Admin notifications" description="Choose which operational events notify the admin team."><div className="grid gap-4 sm:grid-cols-2"><Toggle label="Dispute SLA warnings" description="Notify at 48 and 72 hours." checked={settings.disputeAlerts} onChange={(value) => update("disputeAlerts", value)} /><Toggle label="New verification submissions" description="Notify when Tier 1 or Tier 2 is submitted." checked={settings.verificationAlerts} onChange={(value) => update("verificationAlerts", value)} /></div></SettingsSection></div>
      <aside className="h-fit rounded-xl border border-zinc-200 bg-white p-5"><div className="flex items-center gap-2"><SlidersHorizontal size={18} className="text-violet-600" /><h2 className="font-semibold">Environment</h2></div><div className="mt-5 space-y-4"><Summary label="Mode" value="Production" good /><Summary label="Supabase" value="Connected" good /><Summary label="Escrow rail" value="Manual" /><Summary label="Subscription billing" value="Whop" /><Summary label="Last policy update" value="Jun 18, 2026" /></div><p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs leading-relaxed text-amber-800">Manual escrow is expected for the first 10–20 orders. Keep bank references attached to every ledger entry.</p></aside></div>{toast && <Toast message={toast} onClose={clearToast} />}</div>;
}
function SettingsSection({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-xl border border-zinc-200 bg-white p-5"><div className="flex gap-3"><span className="rounded-lg bg-violet-50 p-2 text-violet-600">{icon}</span><div><h2 className="font-semibold text-zinc-950">{title}</h2><p className="mt-0.5 text-xs text-zinc-500">{description}</p></div></div><div className="mt-5">{children}</div></section>; }
function Field({ label, value, onChange, suffix }: { label: string; value: string; onChange: (value: string) => void; suffix: string }) { return <label><span className="mb-1.5 block text-xs font-medium text-zinc-700">{label}</span><span className="flex h-10 overflow-hidden rounded-lg border border-zinc-200 focus-within:border-violet-400 focus-within:ring-2 focus-within:ring-violet-100"><input value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 px-3 text-sm outline-none" /><span className="flex items-center border-l border-zinc-200 bg-zinc-50 px-3 text-xs text-zinc-500">{suffix}</span></span></label>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <button onClick={() => onChange(!checked)} className="flex w-full items-center justify-between gap-4 rounded-lg border border-zinc-200 p-3 text-left hover:bg-zinc-50"><span><span className="block text-xs font-semibold text-zinc-800">{label}</span><span className="mt-0.5 block text-[11px] text-zinc-500">{description}</span></span><span className={`flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition ${checked ? "bg-violet-600" : "bg-zinc-300"}`}><span className={`h-4 w-4 rounded-full bg-white shadow transition ${checked ? "translate-x-4" : "translate-x-0"}`} /></span></button>; }
function Summary({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="flex items-center justify-between border-b border-zinc-100 pb-3 text-xs last:border-0"><span className="text-zinc-500">{label}</span><span className={`font-semibold ${good ? "text-emerald-600" : "text-zinc-800"}`}>{value}</span></div>; }

